const types = {
  LOADING_COMPETENCIES_START: 'LOADING_PAGE_START',
  LOADING_COMPETENCIES_FINISH: 'LOADING_PAGE_FINISH',
  LOADING_COMPETENCIES_FAILURE: 'LOADING_PAGE_FAILURE',
};

export default types;
